INSERT INTO "public"."courses" ("id", "name", "short_description", "long_description", "total_duration", "price_usd", "currency", "course_link", "purchase_link", "demo_request_link", "level", "category", "language", "thumbnail_url", "rating", "reviews_count", "published", "created_at", "updated_at", "online", "tools_used", "schedule", "original_price_usd", "discount_percentage", "discount_end_date", "min_students", "max_students", "prerequisites", "requirements", "meta_keywords", "meta_description", "syllabus_url", "preview_url", "resources_url") VALUES ('7389b1ea-8a93-4f78-93f3-8efe86937aa5', 'Agentes de IA Autodirigidos: Estrategias para la Optimización Operacional y la Inteligencia de Negocio', 'Capacita a tu equipo en el diseño y despliegue de Agentes de IA autónomos capaces de ejecutar tareas complejas, optimizar procesos y generar insights estratégicos.', 'En la próxima frontera de la Inteligencia Artificial, los **Agentes de IA Autodirigidos** son sistemas capaces de razonar, planificar y ejecutar acciones para alcanzar objetivos complejos de manera autónoma o semi-autónoma.

**Prerrequisitos:** Conocimientos básicos de Python y Machine Learning.  
**Audiencia recomendada:** Arquitectos de soluciones, líderes tecnológicos, gerentes de proyecto y data scientists.

**Evaluación y entregables:**  
- Al finalizar cada módulo habrá un quiz breve.  
- Entregable final: mini-proyecto de diseño de un Agente de IA para un caso de negocio real.

**Recursos y herramientas:**  
- Frameworks: LangChain, AutoGen, CrewAI  
- Repositorios de ejemplo y notebooks de arranque  
- Plantillas: diseño de arquitectura, flujo de memoria, definición de tools

¡Prepara a tu empresa para el futuro de la autonomía inteligente!', '14:00:00', '799.00', 'USD', 'https://tuempresa.com/courses/agentes-autodirigidos-ia', 'https://tuempresa.com/purchase/agentes-autodirigidos-ia', 'https://tuempresa.com/demo/agentes-autodirigidos-ia', 'Avanzado-Experto', 'Inteligencia Artificial, Automatización Avanzada, Estrategia Empresarial, Robótica de Software', 'es', 'https://storage.ecos.ai/thumbnails/agentes-autonomos-thumb.jpg', '4.8', '124', 'true', '2025-06-21 11:31:00.882127+00', '2025-06-21 11:31:00.882127+00', 'true', '"{\"LangChain\",\"OpenAI API\",\"Python\",\"Vector Databases\"]}', 'Martes y Jueves, 19:00 - 21:00 (CDMX)', '1198.500', '33', '2025-07-11 05:49:29.287501+00', '5', '25', '"{\"Conocimientos básicos de Python\",\"Conceptos fundamentales de Machine Learning\",\"Lógica de programación\",\"Inglés técnico básico\"]}', '"{\"Computadora con Python instalado\",\"Conexión estable a internet\",\"5-7 horas semanales de dedicación\",\"Cuenta en OpenAI (proporcionamos créditos)\"]}', '"{[\"agentes autónomos\",\"LangChain\",\"AutoGen\",\"IA avanzada\",\"automatización inteligente\",\"Python IA\"]]}', 'Domina el diseño y desarrollo de Agentes de IA autónomos. Curso práctico con proyectos reales y mentorías personalizadas. ¡Garantía de satisfacción!', 'https://storage.ecos.ai/syllabus/agentes-autonomos-syllabus.pdf', 'https://storage.ecos.ai/preview/agentes-autonomos-preview.mp4', 'https://storage.ecos.ai/resources/agentes-autonomos/'), ('a392bf83-4908-4807-89a9-95d0acc807c9', 'Curso de Inteligencia Artificial para tu día a día profesional desde cero (con ChatGPT e imágenes)', 'Curso práctico de 12 horas dividido en 4 módulos: automatiza tareas, crea documentos, genera imágenes y desarrolla proyectos reales con IA.', 'Este curso, registrado con nombre exacto "Curso de Inteligencia Artificial para tu día a día profesional desde cero (con ChatGPT e imágenes)", ofrece un programa práctico y estructurado para que profesionales sin conocimientos previos integren inteligencia artificial en su trabajo diario. Su contenido está basado exclusivamente en los datos verificados de la base de datos, sin información adicional.

El curso consta de cuatro módulos, cada uno con duración de 3 horas:

ChatGPT como asistente en tareas diarias: Automatización y apoyo en redacción, resumen, traducción y organización de información, usando prompts personalizados. Incluye actividades prácticas para mapear tareas y crear prompts eficaces adaptados al entorno laboral.

Creación de documentos profesionales con ChatGPT: Técnicas para generar, mejorar y personalizar correos, informes y propuestas con IA, usando prompts avanzados y revisión asistida para asegurar claridad y pertinencia.

Generación de imágenes con IA: Uso de DALL·E para crear imágenes profesionales aplicables en presentaciones, redes sociales y materiales educativos, aprendiendo a ajustar prompts visuales según el público y objetivo.

Proyecto personal integrado: Desarrollo de un proyecto real que combine texto e imagen generados con IA, presentación ante colegas, retroalimentación y planificación de uso continuo de IA en el ámbito profesional.

El curso también incluye dinámicas grupales, ejemplos de prompts listos para usar, criterios claros de evaluación y recomendaciones para el uso efectivo y sostenible de IA, alineado a distintos perfiles profesionales.', '12:00:00', '120', 'USD', 'https://tuempresa.com/courses/ia-desde-cero', 'https://tuempresa.com/purchase/Chat-para-tu-dia', 'https://ecosdeliderazgo.com/demo/eco-liderazgo-ia', 'Beginner', 'Inteligencia Artificial', 'es', 'https://storage.ecos.ai/thumbnails/ia-principiantes-thumb.jpg', '4.8', '124', 'true', '2025-06-21 11:11:29.620022+00', '2025-06-21 11:11:29.620022+00', 'true', '"{\"ChatGPT\",\"Midjourney\",\"DALL-E\",\"Canva\"]}', 'Viernes, 17:00 - 19:00 (CDMX)', '180.0', '33', '2025-07-11 05:49:29.287501+00', '5', '25', '"{\"No se requieren conocimientos técnicos previos\",\"Disposición para aprender\",\"Computadora con conexión a internet\"]}', '"{\"Computadora con conexión a internet\",\"3-4 horas semanales de dedicación\",\"Cuenta gratuita en ChatGPT\",\"Cuenta gratuita en Canva\"]}', '"{[\"ChatGPT\",\"IA para principiantes\",\"automatización básica\",\"DALL-E\",\"Midjourney\",\"productividad\"]]}', 'Aprende IA desde cero y multiplica tu productividad. Curso 100% práctico con ejercicios reales y soporte continuo. ¡Sin conocimientos técnicos previos!', 'https://storage.ecos.ai/syllabus/ia-principiantes-syllabus.pdf', 'https://storage.ecos.ai/preview/ia-principiantes-preview.mp4', 'https://storage.ecos.ai/resources/ia-principiantes/'), ('b00f3d1c-e876-4bac-b734-2715110440a0', 'Aprenda y aplique Inteligencia Artificial: Estrategia, Visión y Decisión Aumentada', 'Transforma tu liderazgo con IA. Aprende a anticipar el futuro, optimizar decisiones estratégicas y crear un impacto duradero.', 'En la era de la información, el liderazgo efectivo no solo reacciona, sino que anticipa y moldea el futuro. Este curso de 16 horas, dirigido a CEOs, directores y strategas, te enseñará a integrar IA para:

- **Prerrequisitos:** conocimientos básicos de análisis de datos y conceptos de negocios.
- **Audiencia:** líderes de alto nivel, gerentes senior y responsables de estrategia.
- **Evaluación:** quizzes al final de cada módulo y proyecto final de simulación estratégica.
- **Recursos:** notebooks de ejemplo, plantillas de modelado y enlaces a herramientas de IA.

Aprenderás a usar IA para el análisis predictivo y prescriptivo, la gestión de escenarios, la gobernanza ética y la creación de “ecos” de liderazgo sostenibles.', '16:00:00', '999.00', 'USD', 'https://ecosdeliderazgo.com/courses/eco-liderazgo-ia', 'https://ecosdeliderazgo.com/purchase/eco-liderazgo-ia', 'https://ecosdeliderazgo.com/demo/eco-liderazgo-ia', 'Ejecutivo-Estratégico', 'Liderazgo, Inteligencia Artificial, Estrategia Empresarial, Toma de Decisiones', 'es', 'https://storage.ecos.ai/thumbnails/liderazgo-ia-thumb.jpg', '4.8', '124', 'true', '2025-06-21 11:33:03.604717+00', '2025-06-21 11:33:03.604717+00', 'true', '"{\"Strategia AI Platform\",\"Business Intelligence Tools\",\"Decision Support Systems\"]}', 'Sábados, 09:00 - 13:00 (CDMX)', '1498.500', '33', '2025-07-11 05:49:29.287501+00', '5', '25', '"{\"Experiencia en roles de liderazgo\",\"Comprensión básica de procesos empresariales\",\"Conocimientos básicos de análisis de datos\"]}', '"{\"Computadora con conexión a internet\",\"4-6 horas semanales de dedicación\",\"Casos reales de tu empresa para análisis\",\"Compromiso de implementación\"]}', '"{[\"liderazgo IA\",\"decisiones estratégicas\",\"visión empresarial\",\"futuro del trabajo\",\"transformación digital\"]]}', 'Transforma tu liderazgo con IA. Curso ejecutivo con casos de éxito y networking. ROI garantizado desde la primera semana.', 'https://storage.ecos.ai/syllabus/liderazgo-ia-syllabus.pdf', 'https://storage.ecos.ai/preview/liderazgo-ia-preview.mp4', 'https://storage.ecos.ai/resources/liderazgo-ia/'), ('db747b9e-2872-47a4-a75e-6d6280b1829e', 'Dominando la Automatización Inteligente con IA: Asistentes Virtuales y Análisis Predictivo para Empresas', 'Capacita a tu equipo en las últimas herramientas de IA para automatizar procesos clave, implementar asistentes virtuales avanzados y utilizar el análisis predictivo para una toma de decisiones estratégica en tu empresa.', 'En el dinámico panorama empresarial actual, la eficiencia y la innovación son clave. Este curso intensivo de 10 horas está diseñado para líderes empresariales, gerentes de operaciones, equipos de TI y analistas de datos que buscan transformar sus organizaciones mediante la implementación estratégica de la Inteligencia Artificial.

**Prerrequisitos:** Conocimientos básicos de lógica de programación o experiencia manejando hojas de cálculo.  
**Audiencia recomendada:** Líderes de TI, gerentes de operaciones, equipos de TI, analistas de datos.

**Evaluación:** Al finalizar cada módulo habrá un quiz breve; como entregable final, se presentará un mini-proyecto de implementación de un asistente virtual o modelo predictivo.

**Recursos recomendados:**  
- Plataformas: Dialogflow, Rasa, Azure Bot Service  
- Plantillas: Mapeo de procesos, flujo conversacional, preparación de datos  
- Enlaces: Documentación oficial y tutoriales prácticos  
', '10:00:00', '499.00', 'USD', 'https://tuempresa.com/courses/automacion-inteligente-ia', 'https://tuempresa.com/purchase/automacion-inteligente-ia', 'https://tuempresa.com/demo/automacion-inteligente-ia', 'Intermedio-Avanzado', 'Inteligencia Artificial, Negocios, Automatización', 'es', 'https://storage.ecos.ai/thumbnails/automatizacion-empresarial-thumb.jpg', '4.8', '124', 'true', '2025-06-21 11:25:57.733783+00', '2025-06-21 11:25:57.733783+00', 'true', '"{\"ChatGPT\",\"Zapier\",\"Make.com\",\"Google Sheets\"]}', 'Lunes y Miércoles, 18:00 - 20:00 (CDMX)', '748.500', '33', '2025-07-11 05:49:29.287501+00', '5', '25', '"{\"Familiaridad con hojas de cálculo\",\"Conocimientos básicos de procesos empresariales\",\"Experiencia básica en automatización\"]}', '"{\"Computadora con conexión a internet\",\"4-5 horas semanales de dedicación\",\"Cuenta en Zapier (plan gratuito suficiente)\",\"Microsoft Excel o Google Sheets\"]}', '"{[\"automatización empresarial\",\"asistentes virtuales\",\"análisis predictivo\",\"eficiencia operacional\",\"innovación empresarial\"]]}', 'Automatiza procesos empresariales con IA. Curso práctico con resultados inmediatos. ¡Optimiza operaciones desde el primer día!', 'https://storage.ecos.ai/syllabus/automatizacion-empresarial-syllabus.pdf', 'https://storage.ecos.ai/preview/automatizacion-empresarial-preview.mp4', 'https://storage.ecos.ai/resources/automatizacion-empresarial/');